parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
  project: "./tsconfig.json"
ignorePatterns:
  - "**/__tests__/*"
env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "eslint-config-prettier"